version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgresql
    # environment:
    #   - POSTGRES_USER=admin
    #   - POSTGRES_PASSWORD=admin03
    #   - POSTGRES_DB=dbCarte
    env_file: 
      - ./.env
    volumes:
      - dbCarte-postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    logging:
      options:
        max-size: 10m
        max-file: "3"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: 
      - ./.env
    ports:
      - "5050:80"
volumes:
  dbCarte-postgresql: {}